version: '3.9'

services:
  mongodb:
    image: mongo:6
    container_name: m2c_digital_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  redis:
    image: redis:7
    container_name: m2c_digital_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data: